#!/bin/bash
[ -n "$H_GUARD_UTILS" ] && return
readonly H_GUARD_UTILS=1

function vprintf() {
  if [ -n "$VERBOSE" ]; then
    local argv=("$@")
    local fmt="$1"
    local args=("${argv[@]:1}")
    printf "$fmt" "${args[@]}"
    echo ""
  fi
}

function vecho() {
  if [ -n "$VERBOSE" ]; then
    echo "$@"
  fi
}

function compress_filesystem() {
  echo "[+] re-compressing filesystem..."
  if ! [ -d "$EXTRACTED" ]; then
    _error_exit $FILE_NOT_FOUND "directry '$EXTRACTED' not found"
  fi
  local filetype=$(file $ROOTFS)
  rm -f $ROOTFS

  # copy Drothea
  if [ -f drothea ]; then
    cp drothea "$EXTRACTED/$EXPLOIT_PATH"
  else
    vecho "[-] drothea not found. skipping"
  fi

  # copy Ingrid
  if [ -f ingrid ]; then
    cp ingrid "$EXTRACTED/$EXPLOIT_PATH"
  else
    vecho "[-] ingrid not found. skipping"
  fi

  chmod 777 -R $EXTRACTED
  cd $EXTRACTED
  find ./ -print0 | cpio --owner root --null -o --format=newc >../$ROOTFS || _error_exit $UNKNOWN_ERROR "failed to compress rootfs"
  cd ../
  if [[ $filetype == *"gzip"* ]]; then
    echo "[+] compressing as gzip..."
    mv $ROOTFS tmproot
    gzip tmproot
    mv tmproot.gz $ROOTFS
  fi
}

